# Generated by Django 5.2.1 on 2025-06-02 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_class_roll_user_exam_roll_user_registration_no'),
        ('attendance', '0002_course_day_of_week_course_end_time_course_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.semester'),
        ),
    ]
