# Generated by Django 5.2.1 on 2025-06-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_leaverequest_approved_by_alter_leaverequest_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='mode',
            field=models.CharField(choices=[('rfid', 'RFID'), ('manual_in_person', 'Manual - In Person'), ('manual_online', 'Manual - Online')], default='rfid', max_length=20),
        ),
    ]
