# Generated by Django 5.2.1 on 2025-06-02 10:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_course_day_of_week_remove_course_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='course',
        ),
        migrations.AddField(
            model_name='classsession',
            name='course_schedule',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='attendance.courseschedule'),
            preserve_default=False,
        ),
    ]
