# Generated by Django 5.2.1 on 2025-06-03 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_leaverequest_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaverequest',
            unique_together=set(),
        ),
    ]
