# Generated by Django 5.2.1 on 2025-06-03 04:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_leaverequest_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaverequest',
            unique_together={('student', 'date')},
        ),
    ]
